#!/usr/bin/env python3
"""
GSC Ranking Tracker — aivelocity.dev
Runs weekly, stores data in SQLite, sends Telegram diff report.

Usage:
  python3 gsc_tracker.py           # Full run (query + report + store)
  python3 gsc_tracker.py --test    # Auth test only — prints top 5 queries
  python3 gsc_tracker.py --report  # Report only from stored data (no API call)

Credentials: /root/credentials/aivelocity-gsc-token.json
Generated by: scripts/gsc_auth_local.py (run on Mac)

Schedule (VPS cron): 0 8 * * 1 python3 /root/scripts/gsc_tracker.py
"""

import sys
import json
import sqlite3
import os
import argparse
from datetime import datetime, timedelta, timezone
from pathlib import Path

from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request

# ── Config ────────────────────────────────────────────────────────────────────

SITE_URL        = 'https://aivelocity.dev/'
TOKEN_FILE      = '/root/credentials/aivelocity-gsc-token.json'
DB_FILE         = '/root/data/aivelocity_rankings.db'
TELEGRAM_TOKEN  = os.getenv('TELEGRAM_TOKEN', '')
TELEGRAM_CHAT   = os.getenv('TELEGRAM_CHAT', '')

# Queries to always track (even if not in top results)
PRIORITY_QUERIES = [
    'agentic commerce',
    'agentic payments',
    'agentic marketing',
    'ai commerce',
    'autonomous marketing',
    'machine to machine payments',
    'agentic economy',
]

MIN_IMPRESSIONS = 1   # Include query if at least this many impressions
TOP_N           = 50  # Fetch top N queries from GSC

# ── Auth ──────────────────────────────────────────────────────────────────────

def get_credentials():
    if not os.path.exists(TOKEN_FILE):
        raise FileNotFoundError(
            f"Token file not found: {TOKEN_FILE}\n"
            "Run gsc_auth_local.py on your Mac and copy the result here."
        )

    with open(TOKEN_FILE) as f:
        data = json.load(f)

    creds = Credentials(
        token=data['token'],
        refresh_token=data['refresh_token'],
        token_uri=data['token_uri'],
        client_id=data['client_id'],
        client_secret=data['client_secret'],
        scopes=data['scopes'],
    )

    # Auto-refresh if expired
    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
        data['token'] = creds.token
        with open(TOKEN_FILE, 'w') as f:
            json.dump(data, f, indent=2)

    return creds


def get_service():
    creds = get_credentials()
    return build('searchconsole', 'v1', credentials=creds, cache_discovery=False)


# ── Database ──────────────────────────────────────────────────────────────────

def init_db():
    Path(DB_FILE).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_FILE)
    conn.execute('''
        CREATE TABLE IF NOT EXISTS rankings (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            week_start  TEXT NOT NULL,
            query       TEXT NOT NULL,
            position    REAL,
            impressions INTEGER,
            clicks      INTEGER,
            ctr         REAL,
            recorded_at TEXT NOT NULL
        )
    ''')
    conn.commit()
    return conn


def save_rows(conn, week_start, rows):
    now = datetime.now(timezone.utc).isoformat()
    conn.executemany(
        'INSERT INTO rankings (week_start, query, position, impressions, clicks, ctr, recorded_at) '
        'VALUES (?, ?, ?, ?, ?, ?, ?)',
        [(week_start, r['query'], r['position'], r['impressions'], r['clicks'], r['ctr'], now)
         for r in rows]
    )
    conn.commit()


def get_last_week_rows(conn, week_start):
    # Find the most recent week before this one
    cur = conn.execute(
        "SELECT DISTINCT week_start FROM rankings WHERE week_start < ? ORDER BY week_start DESC LIMIT 1",
        (week_start,)
    )
    row = cur.fetchone()
    if not row:
        return {}
    prev_week = row[0]
    cur = conn.execute(
        "SELECT query, position, impressions, clicks FROM rankings WHERE week_start = ?",
        (prev_week,)
    )
    return {r[0]: {'position': r[1], 'impressions': r[2], 'clicks': r[3]} for r in cur.fetchall()}


# ── GSC API ───────────────────────────────────────────────────────────────────

def fetch_rankings(service, start_date, end_date):
    body = {
        'startDate': start_date,
        'endDate': end_date,
        'dimensions': ['query'],
        'rowLimit': TOP_N,
        'startRow': 0,
    }
    response = service.searchanalytics().query(siteUrl=SITE_URL, body=body).execute()
    rows = response.get('rows', [])

    results = []
    for r in rows:
        results.append({
            'query': r['keys'][0],
            'position': round(r['position'], 1),
            'impressions': r['impressions'],
            'clicks': r['clicks'],
            'ctr': round(r['ctr'] * 100, 2),
        })

    # Add priority queries if missing
    found_queries = {r['query'] for r in results}
    for q in PRIORITY_QUERIES:
        if q not in found_queries:
            # Fetch individually
            body['dimensions'] = ['query']
            body['dimensionFilterGroups'] = [{
                'filters': [{'dimension': 'query', 'operator': 'equals', 'expression': q}]
            }]
            try:
                r = service.searchanalytics().query(siteUrl=SITE_URL, body=body).execute()
                if r.get('rows'):
                    row = r['rows'][0]
                    results.append({
                        'query': q,
                        'position': round(row['position'], 1),
                        'impressions': row['impressions'],
                        'clicks': row['clicks'],
                        'ctr': round(row['ctr'] * 100, 2),
                    })
                else:
                    results.append({
                        'query': q,
                        'position': None,
                        'impressions': 0,
                        'clicks': 0,
                        'ctr': 0.0,
                    })
            except Exception:
                pass
            finally:
                body.pop('dimensionFilterGroups', None)

    return results


# ── Report ────────────────────────────────────────────────────────────────────

def build_report(week_start, current_rows, prev_rows):
    lines = [
        f"AI Velocity Rankings — w/c {week_start}",
        "─" * 42,
    ]

    # Sort: priority queries first, then by impressions desc
    priority_set = set(PRIORITY_QUERIES)

    def sort_key(r):
        is_priority = r['query'] in priority_set
        return (0 if is_priority else 1, -(r['impressions'] or 0))

    sorted_rows = sorted(current_rows, key=sort_key)

    up, down, new, stable, missing = [], [], [], [], []

    for r in sorted_rows:
        q = r['query']
        pos = r['position']
        imp = r['impressions']

        if imp < MIN_IMPRESSIONS and q not in priority_set:
            continue

        if pos is None:
            missing.append(f"  ✗  {q:<35} not in index")
            continue

        prev = prev_rows.get(q)
        if prev is None:
            new.append(f"  NEW {q:<35} pos {pos:.0f}   ({imp} impr)")
        else:
            prev_pos = prev['position']
            delta = prev_pos - pos  # positive = moved up (lower number)
            if delta >= 0.5:
                up.append(f"  ↑  {q:<35} {prev_pos:.0f} → {pos:.0f}   ({imp} impr)")
            elif delta <= -0.5:
                down.append(f"  ↓  {q:<35} {prev_pos:.0f} → {pos:.0f}   ({imp} impr)")
            else:
                stable.append(f"  →  {q:<35} pos {pos:.0f}   ({imp} impr)")

    if up:
        lines.append("IMPROVED")
        lines.extend(up)
    if down:
        lines.append("DROPPED")
        lines.extend(down)
    if new:
        lines.append("NEW")
        lines.extend(new)
    if stable:
        lines.append("STABLE")
        lines.extend(stable)
    if missing:
        lines.append("NOT INDEXED")
        lines.extend(missing)

    # Totals
    lines.append("─" * 42)
    total_imp = sum(r['impressions'] for r in current_rows if r['impressions'])
    total_clicks = sum(r['clicks'] for r in current_rows if r['clicks'])
    avg_pos = None
    positioned = [r['position'] for r in current_rows if r['position']]
    if positioned:
        avg_pos = round(sum(positioned) / len(positioned), 1)

    lines.append(f"Queries tracked: {len(current_rows)}")
    if avg_pos:
        lines.append(f"Avg position:    {avg_pos}")
    lines.append(f"Total impressions: {total_imp:,}")
    lines.append(f"Total clicks:      {total_clicks:,}")

    return "\n".join(lines)


def send_telegram(text):
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT:
        print("[Telegram] Not configured — printing report only")
        return
    import urllib.request, urllib.parse
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = json.dumps({'chat_id': TELEGRAM_CHAT, 'text': text, 'parse_mode': ''}).encode()
    req = urllib.request.Request(url, data=payload, headers={'Content-Type': 'application/json'})
    with urllib.request.urlopen(req) as resp:
        result = json.loads(resp.read())
        if result.get('ok'):
            print("✅ Telegram report sent")
        else:
            print(f"⚠️  Telegram error: {result}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--test', action='store_true', help='Auth test: print top 5 queries')
    parser.add_argument('--report', action='store_true', help='Generate report from stored data only')
    args = parser.parse_args()

    # Date range: last 7 days (Mon–Sun of last complete week)
    today = datetime.now(timezone.utc).date()
    last_monday = today - timedelta(days=today.weekday() + 7)
    last_sunday = last_monday + timedelta(days=6)
    week_start = last_monday.isoformat()
    end_date = last_sunday.isoformat()

    if args.test:
        print("Testing GSC auth...")
        service = get_service()
        rows = fetch_rankings(service, week_start, end_date)
        print(f"\n✅ Auth OK — {len(rows)} queries found for {week_start} to {end_date}\n")
        print("Top 10 by impressions:")
        for r in sorted(rows, key=lambda x: -(x['impressions'] or 0))[:10]:
            pos_str = f"pos {r['position']:.0f}" if r['position'] else "not ranked"
            print(f"  {r['query']:<40} {pos_str}   {r['impressions']} impr")
        return

    conn = init_db()

    if args.report:
        prev_rows = {}
        cur = conn.execute(
            "SELECT DISTINCT week_start FROM rankings ORDER BY week_start DESC LIMIT 2"
        )
        weeks = [r[0] for r in cur.fetchall()]
        if len(weeks) < 2:
            print("Not enough data for comparison yet — run without --report first")
            return
        current_week, prev_week = weeks[0], weeks[1]
        cur_rows_raw = conn.execute(
            "SELECT query, position, impressions, clicks FROM rankings WHERE week_start = ?",
            (current_week,)
        ).fetchall()
        current_rows = [{'query': r[0], 'position': r[1], 'impressions': r[2], 'clicks': r[3], 'ctr': 0}
                        for r in cur_rows_raw]
        prev_rows = get_last_week_rows(conn, current_week)
        report = build_report(current_week, current_rows, prev_rows)
        print(report)
        return

    # Full run
    print(f"Fetching GSC data for {week_start} → {end_date}...")
    service = get_service()
    current_rows = fetch_rankings(service, week_start, end_date)
    print(f"  {len(current_rows)} queries fetched")

    prev_rows = get_last_week_rows(conn, week_start)
    save_rows(conn, week_start, current_rows)
    print(f"  Saved to {DB_FILE}")

    report = build_report(week_start, current_rows, prev_rows)
    print("\n" + report)
    send_telegram(report)


if __name__ == '__main__':
    main()
